[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
zebec_stake = "zSTKzGLiN6T6EVzhBiL6sjULXMahDavAS2p4R62afGv"

[programs.localnet]
zebec_stake = "zSTKzGLiN6T6EVzhBiL6sjULXMahDavAS2p4R62afGv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
stake = "RUST_LOG= yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/stake-zbcn-bankrun.ts"
fetch-pda = "RUST_LOG= yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/fetch-stake-pda.ts"
