[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
stake_zbcn = "zSTKzGLiN6T6EVzhBiL6sjULXMahDavAS2p4R62afGv"

[programs.localnet]
stake_zbcn = "6S5tbu8jPJKFvpBMjaMPQbcwcrw8iHcuGnXH8ZwHgwaE"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/stake-zbcn-bankrun.ts"
